export const mockData = {
  resourceLogs: [
    {
      resource: {
        droppedAttributesCount: 0,
        attributes: [
          { key: "service.namespace", value: { stringValue: "deliverables" } },
          { key: "service.name", value: { stringValue: "sensor" } },
          { key: "service.version", value: { stringValue: "1.5.2" } },
        ],
      },
      scopeLogs: [
        {
          scope: {
            droppedAttributesCount: 0,
            attributes: [
              {
                key: "telemetry.sdk.name",
                value: { stringValue: "dash0-take-home-assignment" },
              },
              {
                key: "telemetry.sdk.language",
                value: { stringValue: "nodejs" },
              },
              { key: "telemetry.sdk.version", value: { stringValue: "1.0.0" } },
            ],
            name: "mock",
          },
          logRecords: [
            {
              timeUnixNano: "1704584043642000000",
              observedTimeUnixNano: "1704584043642000000",
              severityNumber: 21,
              severityText: "FATAL",
              body: { stringValue: "synthesize primary port" },
              attributes: [],
              droppedAttributesCount: 0,
            },
            {
              timeUnixNano: "1705223549129000000",
              observedTimeUnixNano: "1705223549129000000",
              severityNumber: 1,
              severityText: "TRACE",
              body: { stringValue: "generate multi-byte firewall" },
              attributes: [],
              droppedAttributesCount: 0,
            },
            {
              timeUnixNano: "1705528957233000000",
              observedTimeUnixNano: "1705528957233000000",
              severityNumber: 3,
              severityText: "TRACE",
              body: { stringValue: "input 1080p bus" },
              attributes: [],
              droppedAttributesCount: 0,
            },
            {
              timeUnixNano: "1705529862849000000",
              observedTimeUnixNano: "1705529862849000000",
              severityNumber: 13,
              severityText: "WARN",
              body: { stringValue: "copy solid state protocol" },
              attributes: [],
              droppedAttributesCount: 0,
            },
            {
              timeUnixNano: "1705717218569000000",
              observedTimeUnixNano: "1705717218569000000",
              severityNumber: 15,
              severityText: "WARN",
              body: { stringValue: "hack multi-byte feed" },
              attributes: [],
              droppedAttributesCount: 0,
            },
            {
              timeUnixNano: "1705812739588000000",
              observedTimeUnixNano: "1705812739588000000",
              severityNumber: 6,
              severityText: "DEBUG",
              body: { stringValue: "copy open-source port" },
              attributes: [],
              droppedAttributesCount: 0,
            },
            {
              timeUnixNano: "1706221558425000000",
              observedTimeUnixNano: "1706221558425000000",
              severityNumber: 2,
              severityText: "TRACE",
              body: { stringValue: "synthesize bluetooth microchip" },
              attributes: [],
              droppedAttributesCount: 0,
            },
            {
              timeUnixNano: "1706469743832000000",
              observedTimeUnixNano: "1706469743832000000",
              severityNumber: 8,
              severityText: "DEBUG",
              body: { stringValue: "compress digital hard drive" },
              attributes: [],
              droppedAttributesCount: 0,
            },
            {
              timeUnixNano: "1706633273858000000",
              observedTimeUnixNano: "1706633273858000000",
              severityNumber: 5,
              severityText: "DEBUG",
              body: { stringValue: "bypass neural circuit" },
              attributes: [],
              droppedAttributesCount: 0,
            },
          ],
        },
      ],
    },
    {
      resource: {
        droppedAttributesCount: 0,
        attributes: [
          { key: "service.namespace", value: { stringValue: "channels" } },
          { key: "service.name", value: { stringValue: "interface" } },
          { key: "service.version", value: { stringValue: "4.8.2" } },
        ],
      },
      scopeLogs: [
        {
          scope: {
            droppedAttributesCount: 0,
            attributes: [
              {
                key: "telemetry.sdk.name",
                value: { stringValue: "dash0-take-home-assignment" },
              },
              {
                key: "telemetry.sdk.language",
                value: { stringValue: "nodejs" },
              },
              { key: "telemetry.sdk.version", value: { stringValue: "1.0.0" } },
            ],
            name: "mock",
          },
          logRecords: [
            {
              timeUnixNano: "1704068061379000000",
              observedTimeUnixNano: "1704068061379000000",
              severityNumber: 9,
              severityText: "INFO",
              body: { stringValue: "copy mobile array" },
              attributes: [],
              droppedAttributesCount: 0,
            },
            {
              timeUnixNano: "1704397253892000000",
              observedTimeUnixNano: "1704397253892000000",
              severityNumber: 21,
              severityText: "FATAL",
              body: { stringValue: "override online program" },
              attributes: [],
              droppedAttributesCount: 0,
            },
            {
              timeUnixNano: "1704586468693000000",
              observedTimeUnixNano: "1704586468693000000",
              severityNumber: 23,
              severityText: "FATAL",
              body: { stringValue: "index digital application" },
              attributes: [],
              droppedAttributesCount: 0,
            },
            {
              timeUnixNano: "1705392516628000000",
              observedTimeUnixNano: "1705392516628000000",
              severityNumber: 0,
              severityText: "UNSPECIFIED",
              body: { stringValue: "compress bluetooth bandwidth" },
              attributes: [],
              droppedAttributesCount: 0,
            },
            {
              timeUnixNano: "1705838191365000000",
              observedTimeUnixNano: "1705838191365000000",
              severityNumber: 7,
              severityText: "DEBUG",
              body: { stringValue: "parse cross-platform card" },
              attributes: [],
              droppedAttributesCount: 0,
            },
            {
              timeUnixNano: "1705951055947000000",
              observedTimeUnixNano: "1705951055947000000",
              severityNumber: 16,
              severityText: "WARN",
              body: { stringValue: "generate back-end circuit" },
              attributes: [],
              droppedAttributesCount: 0,
            },
            {
              timeUnixNano: "1706285238795000000",
              observedTimeUnixNano: "1706285238795000000",
              severityNumber: 24,
              severityText: "FATAL",
              body: { stringValue: "compress solid state bandwidth" },
              attributes: [],
              droppedAttributesCount: 0,
            },
          ],
        },
      ],
    },
  ],
};
